# This is a basic workflow to help you get started with Actions

name: My Bot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  #envoirnment
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GitHubMail: "nikhil@menghani.com"
  GitHubName: "nikhilmenghani"
  
  
  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: initialization
        run: |
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
             
      - name: installing requirements
        run: |
           pip3 install -r requirements.txt

      - name: running the bot
        timeout-minutes: 300
        continue-on-error: true
        run: |
          python3 nikgappsbot.py

      - name: loop
        run: |
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"main"}'
